services:
  nats:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4222:4222"
      - "8222:8222"
      - "4223:4223"
    networks:
      - nats_network
    restart: always

  mailer:
    build:
      context: ../plan-go-mailer
      dockerfile: Dockerfile
    env_file:
      - .env.docker-compose
    depends_on:
      - nats
    networks:
      - nats_network
    volumes:
      - ../plan-go-mailer:/app
    restart: always

networks:
  nats_network:
