services:
  nats:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4222:4222"
      - "8222:8222"
      - "4223:4223"
    networks:
      - app_network
    restart: unless-stopped

  # api_v1:
  #   build:
  #     context: .
  #     dockerfile: ./WebApp.Api.V1/Dockerfile
  #   env_file:
  #     - .env.docker-compose
  #   depends_on:
  #     - nats
  #   networks:
  #     - app_network
  #   ports:
  #     - "5051:5051"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   restart: always

  mailer:
    build:
      context: ../plan-go-mailer
      dockerfile: Dockerfile
    env_file:
      - ../plan-go-mailer/.env
    depends_on:
      - nats
    networks:
      - app_network
    volumes:
      - ../plan-go-mailer:/app
    restart: always
  
  # hubs:
  #   build:
  #     context: .
  #     dockerfile: ./WebApp.Hubs/Dockerfile
  #   depends_on:
  #     - nats
  #   networks:
  #     - app_network
  #   ports:
  #     - "5054:5054"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   restart: always
  
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webapp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres-data: